---
title: "title"
author:
  - Alisson Rosa Pereira^[@gmail.com]
  - Caroline Cogo Carneosso^[carolcogo808@gmail.com]
  - Renata Figueiredo Stone^[renastan@gmail.com]
  - Vitor Bernardo Silveira Pereira^[@gmail.com]
abstract: "abstract"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
geometry: left=1.7cm, right=1.7cm, top=3cm, bottom=3cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true
---



```{r setup,include=F}

options(digits=3)  #Arrendodamento
options(scipen=999)
ggplot2::theme_set(ggplot2::theme_minimal()) #Tema dos gráficos produzidos no ggplot2
knitr::opts_chunk$set(echo=F,message=F,warning=F,fig.pos = 'H',fig.align = 'center',fig.width=7.8, fig.height=4.85)
scale_fill_discrete = \(...) ggplot2::scale_fill_brewer(... , palette="Set2") #Fixa a scale do fill dos gráficos do ggplot2
#devtools::install_github('https://github.com/AlissonRP/mypdf1/tree/templates')


library(tidyverse)
df <- readxl::read_excel("Questionario pesquisa de mercado .xlsx")

bar_plot <- function(df, v) {
  ggplot(df, aes(
    x = {{ v }},
    y = prop.table(stat(count)),
    fill =  {{ v }},
    label = scales::percent(prop.table(stat(count)))
  )) +
    geom_bar(position = "dodge", color = "black") +
    geom_text(
      stat = "count",
      position = position_dodge(.9),
      vjust = -0.3,
      size = 3.5
    ) +
    scale_y_continuous(labels = scales::percent) +
    scale_fill_brewer(palette = "Set3", drop = FALSE) +
    labs(y = "Proporção", x = df %>%
      select({{ v }}) %>%
      names()) +
    theme(plot.title = element_text(hjust = 0.5, size = 10))
}
to_pt = function(df,v){
  df |> 
    mypdf1::pdf1_tbl_freq({{v}}) |> 
    rename(`n` =  absolute_frequency, `%` = relative_frequency)
}
```



```{r }

df = df |> 
  select(-`Endereço de e-mail`,-`Carimbo de data/hora`,-Pontuação,
         -`Você gostaria de deixar algum comentário sobre o assunto abordado nessa pesquisa?`)

```


```{r bar1, fig.cap="Gráfico de barras relativo aos Cursos do CCNE"}
df |> 
  count(`Curso:`) |> 
  ggplot(aes(`Curso:`,n)) +
  geom_bar(stat = 'identity') +
  coord_flip()
```

A partir da figura \@ref(fig:bar1) podemos observar que obtivemos respostas de todos os cursos do CCNE, 
```{r}
df |> 
 to_pt( `Semestre:`) |> 
  mypdf1::pdf1_tbl('Proporção por curso')
```

```{r}
df |> 
 to_pt( `Você utiliza algum aplicativo ou ferramenta que controla o tempo de uso de plataformas?`) |> 
  mypdf1::pdf1_tbl('Proporção de utilização de aplicativos para controlar tempo')
```



```{r }
df |> 
  mypdf1::pdf1_tbl_freq2(`Sexo:`, `Qual desses dispositivos você mais utiliza ?`)
```

```{r}

df |> 
  mypdf1::pdf1_tbl_freq2(`Sexo:`, `Curso:`)
```



```{r }
df |> 
  mypdf1::pdf1_tbl_freq2(`Qual desses dispositivos você mais utiliza ?`, `Qual plataforma de estudo você tende a utilizar mais?`)
```


```{r}
df |> 
  mypdf1::pdf1_tbl_freq2(`Ocupação:`, `Qual plataforma de estudo você tende a utilizar mais?`)
```


```{r}
df |> 
  mypdf1::pdf1_tbl_freq2(`Ocupação:`, `Qual plataforma de rede social você tende a utilizar mais?`)
```


```{r}
df |> 
  mypdf1::pdf1_tbl_freq2(`Ocupação:`, `Qual desses dispositivos você mais utiliza ?`)
```

```{r }
df |> 
  mypdf1::pdf1_tbl_freq2(`Sexo:`, `Antes da pandemia da Covid-19, em média quanto tempo diário você ficava em frente a tela?`)
```


```{r }
df |> 
  mypdf1::pdf1_tbl_freq2(`Sexo:`, `Qual plataforma de Video Games você tende a utilizar mais ?`)


```

```{r}
df |> 
  mypdf1::pdf1_tbl_freq2(`Antes da pandemia da Covid-19, em média quanto tempo diário você ficava em frente a tela?`,
                         `Atualmente, em média quanto tempo diário você fica em frente a tela?`)
```


```{r}
df |> 
  separate_rows(`Referente a questão anterior qual(is) é o dia que você mais utiliza o dispositivo?`, sep = ', ') |>   bar_plot(`Referente a questão anterior qual(is) é o dia que você mais utiliza o dispositivo?`)+ 
  theme(legend.position = 'none')



  

```


```{r}
df |> 
  separate_rows(`Qual(is) dia(s) da semana você tende a passar mais tempo em plataformas de redes sociais:`, sep = ', ') |>   bar_plot(`Qual(is) dia(s) da semana você tende a passar mais tempo em plataformas de redes sociais:`)+ 
  theme(legend.position = 'none')
```

```{r}
df |> 
  separate_rows(`Qual(is) dia(s) da semana você tende a passar mais tempo em plataformas de streaming :`, sep = ', ') |>   bar_plot(`Qual(is) dia(s) da semana você tende a passar mais tempo em plataformas de streaming :`)+ 
  theme(legend.position = 'none')
```

```{r}
df |> 
  separate_rows(`Qual(is) dia(s) da semana você tende a passar mais tempo em plataformas de estudo :`, sep = ', ') |>   bar_plot(`Qual(is) dia(s) da semana você tende a passar mais tempo em plataformas de estudo :`)+ 
  theme(legend.position = 'none')
```

# Bibliography {-}



